//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Density.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Density.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///  &quot;aircraft&quot;: &quot;Boeing 737&quot;,
        ///  &quot;speed&quot;: &quot;340&quot;
        ///  },
        ///  {
        ///  &quot;aircraft&quot;: &quot;Gulfstream 5&quot;,
        ///  &quot;speed&quot;: &quot;300&quot;
        ///  },
        ///   {
        ///  &quot;aircraft&quot;: &quot;KingAir 350&quot;,
        ///  &quot;speed&quot;: &quot;300&quot;
        ///  },
        ///   {
        ///  &quot;aircraft&quot;: &quot;Lear 45&quot;,
        ///  &quot;speed&quot;: &quot;465&quot;
        ///  }].
        /// </summary>
        public static string Aircraft {
            get {
                return ResourceManager.GetString("Aircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///  &quot;MapsAPI&quot;: &quot;AIzaSyA7_xqTgHHdFo6Fe19OmcVpkF7If4Vz8Zw&quot;
        ///  }].
        /// </summary>
        public static string Keys {
            get {
                return ResourceManager.GetString("Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///  &quot;state&quot;: &quot;Pennsylvania&quot;,
        ///  &quot;city&quot;: &quot;Allentown&quot;,
        ///  &quot;name&quot;: &quot;Lehigh Valley International Airport&quot;,
        ///  &quot;icao&quot;: &quot;KABE&quot;,
        ///  &quot;lat&quot;: &quot;40.6514&quot;,
        ///  &quot;lon&quot;: &quot;-75.4342&quot;
        ///},
        ///{
        ///  &quot;state&quot;: &quot;Texas&quot;,
        ///  &quot;city&quot;: &quot;Abilene&quot;,
        ///  &quot;name&quot;: &quot;Abilene Regional Airport&quot;,
        ///  &quot;icao&quot;: &quot;KABI&quot;,
        ///  &quot;lat&quot;: &quot;32.4164&quot;,
        ///  &quot;lon&quot;: &quot;-99.6803&quot;
        ///},
        ///{
        ///  &quot;state&quot;: &quot;Alaska&quot;,
        ///  &quot;city&quot;: &quot;Kiana&quot;,
        ///  &quot;name&quot;: &quot;Ambler Airport&quot;,
        ///  &quot;icao&quot;: &quot;PAIK&quot;,
        ///  &quot;lat&quot;: &quot;67.1058&quot;,
        ///  &quot;lon&quot;: &quot;-157.854&quot;
        ///},
        ///{
        ///  &quot;state&quot;: &quot;New Mexico&quot;,
        ///  &quot;city&quot;: &quot;Albuquerque&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///  &quot;Juneau&quot;: &quot;https://weathercams.faa.gov/map/-136.49545,56.88676,-128.82699,59.76355/airport/JNU/details/camera/10018&quot;
        ///  }].
        /// </summary>
        public static string WeatherCams {
            get {
                return ResourceManager.GetString("WeatherCams", resourceCulture);
            }
        }
    }
}
